https://pandas.pydata.org/pandas-docs/stable/reference/index.html

# Apply method

In [5]:
import pandas as pd
import numpy as np

In [6]:
df=pd.read_csv('tips.csv')
df.head()

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID
0,16.99,1.01,Female,No,Sun,Dinner,2,8.49,Christy Cunningham,3560325168603410,Sun2959
1,10.34,1.66,Male,No,Sun,Dinner,3,3.45,Douglas Tucker,4478071379779230,Sun4608
2,21.01,3.50,Male,No,Sun,Dinner,3,7.00,Travis Walters,6011812112971322,Sun4458
3,23.68,3.31,Male,No,Sun,Dinner,2,11.84,Nathaniel Harris,4676137647685994,Sun5260
4,24.59,3.61,Female,No,Sun,Dinner,4,6.15,Tonya Carter,4832732618637221,Sun2251

In [7]:
'*'*12+str(3560325168603410)[-4:]

'************3410'

In [8]:
def last_four_digits(num):
    return '*'*12+str(num)[-4:]

In [9]:
last_four_digits(123456789123456789)

'************6789'

In [10]:
df['CC Number']

0      3560325168603410
1      4478071379779230
2      6011812112971322
3      4676137647685994
4      4832732618637221
             ...
239    5296068606052842
240    3506806155565404
241    6011891618747196
242       4375220550950
243    3511451626698139
Name: CC Number, Length: 244, dtype: int64

In [11]:
df['masked_CC']= df['CC Number'].apply(last_four_digits)

In [12]:
df.head()

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID,masked_CC
0,16.99,1.01,Female,No,Sun,Dinner,2,8.49,Christy Cunningham,3560325168603410,Sun2959,************3410
1,10.34,1.66,Male,No,Sun,Dinner,3,3.45,Douglas Tucker,4478071379779230,Sun4608,************9230
2,21.01,3.50,Male,No,Sun,Dinner,3,7.00,Travis Walters,6011812112971322,Sun4458,************1322
3,23.68,3.31,Male,No,Sun,Dinner,2,11.84,Nathaniel Harris,4676137647685994,Sun5260,************5994
4,24.59,3.61,Female,No,Sun,Dinner,4,6.15,Tonya Carter,4832732618637221,Sun2251,************7221

In [13]:
df['CC Number'].apply(lambda num: '*'*12+str(num)[-4:])

0      ************3410
1      ************9230
2      ************1322
3      ************5994
4      ************7221
             ...
239    ************2842
240    ************5404
241    ************7196
242    ************0950
243    ************8139
Name: CC Number, Length: 244, dtype: object

In [14]:
df['final_bill']= df['total_bill'].apply(lambda amt: np.round(1.05*amt,2))

In [15]:
df.head()

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID,masked_CC,final_bill
0,16.99,1.01,Female,No,Sun,Dinner,2,8.49,Christy Cunningham,3560325168603410,Sun2959,************3410,17.84
1,10.34,1.66,Male,No,Sun,Dinner,3,3.45,Douglas Tucker,4478071379779230,Sun4608,************9230,10.86
2,21.01,3.50,Male,No,Sun,Dinner,3,7.00,Travis Walters,6011812112971322,Sun4458,************1322,22.06
3,23.68,3.31,Male,No,Sun,Dinner,2,11.84,Nathaniel Harris,4676137647685994,Sun5260,************5994,24.86
4,24.59,3.61,Female,No,Sun,Dinner,4,6.15,Tonya Carter,4832732618637221,Sun2251,************7221,25.82

In [16]:
df.describe() #statistical summary

,total_bill,tip,size,price_per_person,CC Number,final_bill
count,244.000000,244.000000,244.000000,244.000000,2.440000e+02,244.000000
mean,19.785943,2.998279,2.569672,7.888197,2.563496e+15,20.774877
std,8.902412,1.383638,0.951100,2.914234,2.369340e+15,9.347566
min,3.070000,1.000000,1.000000,2.880000,6.040679e+10,3.220000
25%,13.347500,2.000000,2.000000,5.800000,3.040731e+13,14.015000
50%,17.795000,2.900000,2.000000,7.255000,3.525318e+15,18.685000
75%,24.127500,3.562500,3.000000,9.390000,4.553675e+15,25.330000
max,50.810000,10.000000,6.000000,20.270000,6.596454e+15,53.350000

In [17]:
df.describe().transpose()

,count,mean,std,min,25%,50%,75%,max
total_bill,244.0,1.978594e+01,8.902412e+00,3.070000e+00,1.334750e+01,1.779500e+01,2.412750e+01,5.081000e+01
tip,244.0,2.998279e+00,1.383638e+00,1.000000e+00,2.000000e+00,2.900000e+00,3.562500e+00,1.000000e+01
size,244.0,2.569672e+00,9.510998e-01,1.000000e+00,2.000000e+00,2.000000e+00,3.000000e+00,6.000000e+00
price_per_person,244.0,7.888197e+00,2.914234e+00,2.880000e+00,5.800000e+00,7.255000e+00,9.390000e+00,2.027000e+01
CC Number,244.0,2.563496e+15,2.369340e+15,6.040679e+10,3.040731e+13,3.525318e+15,4.553675e+15,6.596454e+15
final_bill,244.0,2.077488e+01,9.347566e+00,3.220000e+00,1.401500e+01,1.868500e+01,2.533000e+01,5.335000e+01

### Sort Values

In [18]:
df.sort_values('tip')

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID,masked_CC,final_bill
92,5.75,1.00,Female,Yes,Fri,Dinner,2,2.88,Leah Ramirez,3508911676966392,Fri3780,************6392,6.04
111,7.25,1.00,Female,No,Sat,Dinner,1,7.25,Terri Jones,3559221007826887,Sat4801,************6887,7.61
67,3.07,1.00,Female,Yes,Sat,Dinner,1,3.07,Tiffany Brock,4359488526995267,Sat3455,************5267,3.22
236,12.60,1.00,Male,Yes,Sat,Dinner,2,6.30,Matthew Myers,3543676378973965,Sat5032,************3965,13.23
0,16.99,1.01,Female,No,Sun,Dinner,2,8.49,Christy Cunningham,3560325168603410,Sun2959,************3410,17.84
...,...,...,...,...,...,...,...,...,...,...,...,...,...
141,34.30,6.70,Male,No,Thur,Lunch,6,5.72,Steven Carlson,3526515703718508,Thur1025,************8508,36.02
59,48.27,6.73,Male,No,Sat,Dinner,4,12.07,Brian Ortiz,6596453823950595,Sat8139,************0595,50.68
23,39.42,7.58,Male,No,Sat,Dinner,4,9.86,Lance Peterson,3542584061609808,Sat239,************9808,41.39
212,48.33,9.00,Male,No,Sat,Dinner,4,12.08,Alex Williamson,676218815212,Sat4590,************5212,50.75
170,50.81,10.00,Male,Yes,Sat,Dinner,3,16.94,Gregory Clark,5473850968388236,Sat1954,************8236,53.35

In [19]:
df.sort_values('tip',ascending=False)

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID,masked_CC,final_bill
170,50.81,10.00,Male,Yes,Sat,Dinner,3,16.94,Gregory Clark,5473850968388236,Sat1954,************8236,53.35
212,48.33,9.00,Male,No,Sat,Dinner,4,12.08,Alex Williamson,676218815212,Sat4590,************5212,50.75
23,39.42,7.58,Male,No,Sat,Dinner,4,9.86,Lance Peterson,3542584061609808,Sat239,************9808,41.39
59,48.27,6.73,Male,No,Sat,Dinner,4,12.07,Brian Ortiz,6596453823950595,Sat8139,************0595,50.68
141,34.30,6.70,Male,No,Thur,Lunch,6,5.72,Steven Carlson,3526515703718508,Thur1025,************8508,36.02
...,...,...,...,...,...,...,...,...,...,...,...,...,...
0,16.99,1.01,Female,No,Sun,Dinner,2,8.49,Christy Cunningham,3560325168603410,Sun2959,************3410,17.84
111,7.25,1.00,Female,No,Sat,Dinner,1,7.25,Terri Jones,3559221007826887,Sat4801,************6887,7.61
92,5.75,1.00,Female,Yes,Fri,Dinner,2,2.88,Leah Ramirez,3508911676966392,Fri3780,************6392,6.04
67,3.07,1.00,Female,Yes,Sat,Dinner,1,3.07,Tiffany Brock,4359488526995267,Sat3455,************5267,3.22
236,12.60,1.00,Male,Yes,Sat,Dinner,2,6.30,Matthew Myers,3543676378973965,Sat5032,************3965,13.23

### Correlation

In [20]:
df.corr()

ValueError: could not convert string to float: 'Female'

In [21]:
df.corr(numeric_only=True)

,total_bill,tip,size,price_per_person,CC Number,final_bill
total_bill,1.000000,0.675734,0.598315,0.647554,0.104576,1.000000
tip,0.675734,1.000000,0.489299,0.347405,0.110857,0.675736
size,0.598315,0.489299,1.000000,-0.175359,-0.030239,0.598330
price_per_person,0.647554,0.347405,-0.175359,1.000000,0.135240,0.647526
CC Number,0.104576,0.110857,-0.030239,0.135240,1.000000,0.104569
final_bill,1.000000,0.675736,0.598330,0.647526,0.104569,1.000000

### idxmin and idxmax

In [22]:
df['tip'].idxmax()

170

In [23]:
df['tip'].idxmin()

67

In [24]:
df['tip'].max()

10.0

In [25]:
df['tip'].min()

1.0

### Value Counts

In [26]:
df.head(3)

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID,masked_CC,final_bill
0,16.99,1.01,Female,No,Sun,Dinner,2,8.49,Christy Cunningham,3560325168603410,Sun2959,************3410,17.84
1,10.34,1.66,Male,No,Sun,Dinner,3,3.45,Douglas Tucker,4478071379779230,Sun4608,************9230,10.86
2,21.01,3.50,Male,No,Sun,Dinner,3,7.00,Travis Walters,6011812112971322,Sun4458,************1322,22.06

In [27]:
df['time'].value_counts()

time
Dinner    176
Lunch      68
Name: count, dtype: int64

In [28]:
df['day'].value_counts()

day
Sat     87
Sun     76
Thur    62
Fri     19
Name: count, dtype: int64

### Replace

In [29]:
df['day'].replace(to_replace='Sun',value='Sunday')

0      Sunday
1      Sunday
2      Sunday
3      Sunday
4      Sunday
        ...
239       Sat
240       Sat
241       Sat
242       Sat
243      Thur
Name: day, Length: 244, dtype: object

### Unique

In [30]:
df['day'].unique()

array(['Sun', 'Sat', 'Thur', 'Fri'], dtype=object)

In [31]:
df['day'].nunique()

4

### Map

In [32]:
my_values={'Female':'F',
           'Male':'M'}

In [33]:
df('sex').map(my_values)

TypeError: 'DataFrame' object is not callable

In [34]:
df['sex'].map(my_values)

0      F
1      M
2      M
3      M
4      F
      ..
239    M
240    F
241    M
242    M
243    F
Name: sex, Length: 244, dtype: object

### Duplicates

In [35]:
df.duplicated()

0      False
1      False
2      False
3      False
4      False
       ...
239    False
240    False
241    False
242    False
243    False
Length: 244, dtype: bool

In [36]:
df[df.duplicated()]

Empty DataFrame
Columns: [total_bill, tip, sex, smoker, day, time, size, price_per_person, Payer Name, CC Number, Payment ID, masked_CC, final_bill]
Index: []

In [37]:
simple_df = pd.DataFrame([1,2,3,3],
                         ['a','b','c','d'])

In [38]:
simple_df.duplicated()

a    False
b    False
c    False
d     True
dtype: bool

In [39]:
simple_df[simple_df.duplicated()]

   0
d  3

In [40]:
simple_df.drop_duplicates()

   0
a  1
b  2
c  3

### Between

In [41]:
df[df['total_bill'].between(15,17)]

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID,masked_CC,final_bill
0,16.99,1.01,Female,No,Sun,Dinner,2,8.49,Christy Cunningham,3560325168603410,Sun2959,************3410,17.84
8,15.04,1.96,Male,No,Sun,Dinner,2,7.52,Joseph Mcdonald,3522866365840377,Sun6820,************0377,15.79
12,15.42,1.57,Male,No,Sun,Dinner,2,7.71,Chad Harrington,577040572932,Sun1300,************2932,16.19
17,16.29,3.71,Male,No,Sun,Dinner,3,5.43,John Pittman,6521340257218708,Sun2998,************8708,17.10
18,16.97,3.50,Female,No,Sun,Dinner,3,5.66,Laura Martinez,30422275171379,Sun2789,************1379,17.82
22,15.77,2.23,Female,No,Sat,Dinner,2,7.88,Ashley Shelton,3524119516293213,Sat9786,************3213,16.56
32,15.06,3.00,Female,No,Sat,Dinner,2,7.53,Amanda Wilson,213186304291560,Sat1327,************1560,15.81
36,16.31,2.00,Male,No,Sat,Dinner,3,5.44,William Ford,3527691170179398,Sat9139,************9398,17.13
37,16.93,3.07,Female,No,Sat,Dinner,3,5.64,Erin Lewis,5161695527390786,Sat6406,************0786,17.78
40,16.04,2.24,Male,No,Sat,Dinner,3,5.35,Adam Edwards,3544447755679420,Sat8549,************9420,16.84
66,16.45,2.47,Female,No,Sat,Dinner,2,8.22,Rachel Vaughn,3569262692675583,Sat4750,************5583,17.27
69,15.01,2.09,Male,Yes,Sat,Dinner,2,7.50,Adam Hall,4700924377057571,Sat855,************7571,15.76
81,16.66,3.40,Male,No,Thur,Lunch,2,8.33,William Martin,4550549048402707,Thur8232,************2707,17.49
84,15.98,2.03,Male,No,Thur,Lunch,2,7.99,Jason Jones,4442984204923315,Thur1944,************3315,16.78
93,16.32,4.30,Female,Yes,Fri,Dinner,2,8.16,Natalie Nguyen,5181236182893396,Fri6963,************3396,17.14
101,15.38,3.00,Female,Yes,Fri,Dinner,2,7.69,Tiffany Colon,6011012799432041,Fri8382,************2041,16.15
105,15.36,1.64,Male,Yes,Sat,Dinner,2,7.68,David Price,4029957452720,Sat5106,************2720,16.13
123,15.95,2.00,Male,No,Thur,Lunch,2,7.98,Christopher Lang,4820629318698319,Thur1992,************8319,16.75
138,16.00,2.00,Male,Yes,Thur,Lunch,2,8.00,Jason Burgess,3561461821942363,Thur2710,************2363,16.80
144,16.43,2.30,Female,No,Thur,Lunch,2,8.22,Linda Jones,6542729219645658,Thur9002,************5658,17.25
159,16.49,2.00,Male,No,Sun,Dinner,4,4.12,Christopher Soto,30501814271434,Sun1781,************1434,17.31
162,16.21,2.00,Female,No,Sun,Dinner,3,5.40,Jennifer Baird,4227834176859693,Sun5521,************9693,17.02
171,15.81,3.16,Male,Yes,Sat,Dinner,2,7.90,David Hall,502004138207,Sat6750,************8207,16.60
174,16.82,4.00,Male,Yes,Sun,Dinner,2,8.41,Brian Miles,3586342145399277,Sun7621,************9277,17.66
190,15.69,1.50,Male,Yes,Sun,Dinner,2,7.84,Riley Barnes,180053549128800,Sun5104,************8800,16.47
193,15.48,2.02,Male,Yes,Thur,Lunch,2,7.74,Raymond Sullivan,180068856139315,Thur606,************9315,16.25
194,16.58,4.00,Male,Yes,Thur,Lunch,2,8.29,Benjamin Weber,676210011505,Thur9318,************1505,17.41
203,16.40,2.50,Female,Yes,Thur,Lunch,2,8.20,Toni Brooks,3582289985920239,Thur7770,************0239,17.22
205,16.47,3.23,Female,Yes,Thur,Lunch,3,5.49,Carly Reyes,4787787236486,Thur8084,************6486,17.29
223,15.98,3.00,Female,No,Fri,Lunch,3,5.33,Mary Rivera,5343428579353069,Fri6014,************3069,16.78
225,16.27,2.50,Female,Yes,Fri,Lunch,2,8.14,Whitney Arnold,3579111947217428,Fri6665,************7428,17.08
231,15.69,3.00,Male,Yes,Sat,Dinner,3,5.23,Jason Parks,4812333796161,Sat6334,************6161,16.47
234,15.53,3.00,Male,Yes,Sat,Dinner,2,7.76,Tracy Douglas,4097938155941930,Sat7220,************1930,16.31