In [1]:
import numpy as np
import pandas as pd

In [2]:
np.nan

nan

In [3]:
type(np.nan)

float

In [4]:
pd.NA

In [5]:
type(pd.NA)

pandas._libs.missing.NAType

In [6]:
pd.NaT

NaT

In [7]:
type(pd.NaT)

pandas._libs.tslibs.nattype.NaTType

In [8]:
np.nan == np.nan

False

In [10]:
np.nan in [np.nan,12,'hi','hello'] #this is only checking that whether we have null values in it or not

True

In [11]:
df= pd.read_csv('movie_scores.csv')
df.head()

  first_name last_name   age  sex  pre_movie_score  post_movie_score
0        Tom     Hanks  63.0    m              8.0              10.0
1        NaN       NaN   NaN  NaN              NaN               NaN
2       Hugh   Jackman  51.0    m              NaN               NaN
3      Oprah   Winfrey  66.0    f              6.0               8.0
4       Emma     Stone  31.0    f              7.0               9.0

In [12]:
df.isnull()

   first_name  last_name    age    sex  pre_movie_score  post_movie_score
0       False      False  False  False            False             False
1        True       True   True   True             True              True
2       False      False  False  False             True              True
3       False      False  False  False            False             False
4       False      False  False  False            False             False

In [13]:
df.notnull()

   first_name  last_name    age    sex  pre_movie_score  post_movie_score
0        True       True   True   True             True              True
1       False      False  False  False            False             False
2        True       True   True   True            False             False
3        True       True   True   True             True              True
4        True       True   True   True             True              True

In [14]:
df.isnull.sum()

AttributeError: 'function' object has no attribute 'sum'

In [16]:
df.isnull().sum() #given no of missing values in each column

first_name          1
last_name           1
age                 1
sex                 1
pre_movie_score     2
post_movie_score    2
dtype: int64

In [18]:
df.isna().sum() #same ans as above

first_name          1
last_name           1
age                 1
sex                 1
pre_movie_score     2
post_movie_score    2
dtype: int64

In [19]:
df['first_name'].isnull()

0    False
1     True
2    False
3    False
4    False
Name: first_name, dtype: bool

In [20]:
df[df['first_name'].isnull()]

  first_name last_name  age  sex  pre_movie_score  post_movie_score
1        NaN       NaN  NaN  NaN              NaN               NaN

In [22]:
df[(df['pre_movie_score'].isnull()) & (df['sex'].notnull())]

  first_name last_name   age sex  pre_movie_score  post_movie_score
2       Hugh   Jackman  51.0   m              NaN               NaN

### Drop Data

In [23]:
df

  first_name last_name   age  sex  pre_movie_score  post_movie_score
0        Tom     Hanks  63.0    m              8.0              10.0
1        NaN       NaN   NaN  NaN              NaN               NaN
2       Hugh   Jackman  51.0    m              NaN               NaN
3      Oprah   Winfrey  66.0    f              6.0               8.0
4       Emma     Stone  31.0    f              7.0               9.0

In [24]:
df.dropna() #Imp

  first_name last_name   age sex  pre_movie_score  post_movie_score
0        Tom     Hanks  63.0   m              8.0              10.0
3      Oprah   Winfrey  66.0   f              6.0               8.0
4       Emma     Stone  31.0   f              7.0               9.0

In [26]:
df

  first_name last_name   age  sex  pre_movie_score  post_movie_score
0        Tom     Hanks  63.0    m              8.0              10.0
1        NaN       NaN   NaN  NaN              NaN               NaN
2       Hugh   Jackman  51.0    m              NaN               NaN
3      Oprah   Winfrey  66.0    f              6.0               8.0
4       Emma     Stone  31.0    f              7.0               9.0

In [32]:
df.dropna(thresh=1) #here axis=0, this means we are dropping the rows in this case

  first_name last_name   age sex  pre_movie_score  post_movie_score
0        Tom     Hanks  63.0   m              8.0              10.0
2       Hugh   Jackman  51.0   m              NaN               NaN
3      Oprah   Winfrey  66.0   f              6.0               8.0
4       Emma     Stone  31.0   f              7.0               9.0

In [28]:
df.dropna(thresh=2)

  first_name last_name   age sex  pre_movie_score  post_movie_score
0        Tom     Hanks  63.0   m              8.0              10.0
2       Hugh   Jackman  51.0   m              NaN               NaN
3      Oprah   Winfrey  66.0   f              6.0               8.0
4       Emma     Stone  31.0   f              7.0               9.0

In [29]:
df.dropna(thresh=3)

  first_name last_name   age sex  pre_movie_score  post_movie_score
0        Tom     Hanks  63.0   m              8.0              10.0
2       Hugh   Jackman  51.0   m              NaN               NaN
3      Oprah   Winfrey  66.0   f              6.0               8.0
4       Emma     Stone  31.0   f              7.0               9.0

In [30]:
df.dropna(thresh=4)

  first_name last_name   age sex  pre_movie_score  post_movie_score
0        Tom     Hanks  63.0   m              8.0              10.0
2       Hugh   Jackman  51.0   m              NaN               NaN
3      Oprah   Winfrey  66.0   f              6.0               8.0
4       Emma     Stone  31.0   f              7.0               9.0

In [31]:
df.dropna(thresh=5)

  first_name last_name   age sex  pre_movie_score  post_movie_score
0        Tom     Hanks  63.0   m              8.0              10.0
3      Oprah   Winfrey  66.0   f              6.0               8.0
4       Emma     Stone  31.0   f              7.0               9.0

In [33]:
df.dropna(axis=1)

Empty DataFrame
Columns: []
Index: [0, 1, 2, 3, 4]

In [34]:
df.dropna(axis=1,thresh=1)

  first_name last_name   age  sex  pre_movie_score  post_movie_score
0        Tom     Hanks  63.0    m              8.0              10.0
1        NaN       NaN   NaN  NaN              NaN               NaN
2       Hugh   Jackman  51.0    m              NaN               NaN
3      Oprah   Winfrey  66.0    f              6.0               8.0
4       Emma     Stone  31.0    f              7.0               9.0

In [35]:
df.dropna(axis=1,thresh=4)

  first_name last_name   age  sex
0        Tom     Hanks  63.0    m
1        NaN       NaN   NaN  NaN
2       Hugh   Jackman  51.0    m
3      Oprah   Winfrey  66.0    f
4       Emma     Stone  31.0    f

### Fill Data

In [36]:
df

  first_name last_name   age  sex  pre_movie_score  post_movie_score
0        Tom     Hanks  63.0    m              8.0              10.0
1        NaN       NaN   NaN  NaN              NaN               NaN
2       Hugh   Jackman  51.0    m              NaN               NaN
3      Oprah   Winfrey  66.0    f              6.0               8.0
4       Emma     Stone  31.0    f              7.0               9.0

In [37]:
df.fillna('Empty!!')

  first_name last_name      age      sex pre_movie_score post_movie_score
0        Tom     Hanks     63.0        m             8.0             10.0
1    Empty!!   Empty!!  Empty!!  Empty!!         Empty!!          Empty!!
2       Hugh   Jackman     51.0        m         Empty!!          Empty!!
3      Oprah   Winfrey     66.0        f             6.0              8.0
4       Emma     Stone     31.0        f             7.0              9.0

In [38]:
df['first_name'].fillna('No name here!!')

0               Tom
1    No name here!!
2              Hugh
3             Oprah
4              Emma
Name: first_name, dtype: object

In [39]:
df['first_name']=df['first_name'].fillna('No name here!!')

In [40]:
df

       first_name last_name   age  sex  pre_movie_score  post_movie_score
0             Tom     Hanks  63.0    m              8.0              10.0
1  No name here!!       NaN   NaN  NaN              NaN               NaN
2            Hugh   Jackman  51.0    m              NaN               NaN
3           Oprah   Winfrey  66.0    f              6.0               8.0
4            Emma     Stone  31.0    f              7.0               9.0

In [41]:
df['pre_movie_score'].mean()

np.float64(7.0)

In [42]:
df['pre_movie_score'].fillna(df['pre_movie_score'].mean())

0    8.0
1    7.0
2    7.0
3    6.0
4    7.0
Name: pre_movie_score, dtype: float64

In [43]:
df.fillna(df.mean(numeric_only=True))

       first_name last_name    age  sex  pre_movie_score  post_movie_score
0             Tom     Hanks  63.00    m              8.0              10.0
1  No name here!!       NaN  52.75  NaN              7.0               9.0
2            Hugh   Jackman  51.00    m              7.0               9.0
3           Oprah   Winfrey  66.00    f              6.0               8.0
4            Emma     Stone  31.00    f              7.0               9.0